[package]
name = "capture-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
autobins = false

[dependencies]
anyhow.workspace = true
capture-protocol = { path = "../capture-protocol" }
clap.workspace = true
ctrlc.workspace = true
serde.workspace = true
serde_json.workspace = true
image.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
x11rb.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_Storage_Xps",
    "Win32_Storage_FileSystem",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(target_os = "macos")'.dependencies]
screencapturekit.workspace = true

[dev-dependencies]
tempfile = "3.20"
